# Generated by Django 6.1.1 on 2026-09-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_assistancerequest_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='service',
            field=models.CharField(choices=[('Mechanical Assistance', 'Mechanical Assistance'), ('Battery Assistance', 'Battery Assistance'), ('Tyre Assistance', 'Tyre Assistance'), ('Fuel Assistance', 'Fuel Assistance'), ('Towing Service', 'Towing Service'), ('Lockout Assistance', 'Lockout Assistance'), ('Engine Overheating', 'Engine Overheating'), ('Accident Assistance', 'Accident Assistance'), ('Fuel Delivery', 'Fuel Delivery'), ('Emergency Roadside', 'Emergency Roadside'), ('Vehicle Inspection', 'Vehicle Inspection'), ('Roadside Support', 'Roadside Support')], max_length=100),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Service Started', 'Service Started'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
