# Generated by Django 6.1.1 on 2026-09-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_assistancerequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Available', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='vehicle.mechanic')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='vehicle.assistancerequest')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
